
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cuecard.fullname" . }}-secret
type: Opaque
stringData:
  DATABASE_URL: "{{ required "secretEnv.DATABASE_URL is required" .Values.secretEnv.DATABASE_URL }}"
  OPENAI_API_KEY: "{{ .Values.secretEnv.OPENAI_API_KEY }}"
  CUECARD_API_KEY: "{{ required "secretEnv.CUECARD_API_KEY is required" .Values.secretEnv.CUECARD_API_KEY }}"
