
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cuecard.fullname" . }}-secret
type: Opaque
stringData:
  OPENAI_API_KEY: "{{ .Values.secretEnv.OPENAI_API_KEY }}"
  CUECARD_API_KEY: "{{ .Values.secretEnv.CUECARD_API_KEY }}"
